"""expand_behandelplan_with_all_fields

Revision ID: 38f019826947
Revises: ccce2400e8b0
Create Date: 2026-01-30 10:43:42.170109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f019826947'
down_revision: Union[str, None] = 'ccce2400e8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behandelplan', sa.Column('toedracht', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('causaliteitsvraag', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('dekking', sa.Boolean(), nullable=True))
    op.add_column('behandelplan', sa.Column('percentage_aansprakelijkheid', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('behandelplan', sa.Column('datum_aansprakelijkheid', sa.Date(), nullable=True))
    op.add_column('behandelplan', sa.Column('percentage_eigen_schuld', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('behandelplan', sa.Column('regres_mogelijk', sa.Boolean(), nullable=True))
    op.add_column('behandelplan', sa.Column('alle_of_niets_dossier', sa.Boolean(), nullable=True))
    op.add_column('behandelplan', sa.Column('letselsoort', sa.String(length=255), nullable=True))
    op.add_column('behandelplan', sa.Column('letselspecificatie', sa.String(length=255), nullable=True))
    op.add_column('behandelplan', sa.Column('letsel_zijde', sa.String(length=50), nullable=True))
    op.add_column('behandelplan', sa.Column('dominante_zijde_beinvloedt', sa.Boolean(), nullable=True))
    op.add_column('behandelplan', sa.Column('klachten', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('diagnose', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('beperkingen', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('bijzonderheden_pre_existente', sa.Boolean(), nullable=True))
    op.add_column('behandelplan', sa.Column('hersteld', sa.Boolean(), nullable=True))
    op.add_column('behandelplan', sa.Column('datum_eindsituatie', sa.Date(), nullable=True))
    op.add_column('behandelplan', sa.Column('medisch_advies', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('beroep', sa.String(length=255), nullable=True))
    op.add_column('behandelplan', sa.Column('dienstverband', sa.String(length=100), nullable=True))
    op.add_column('behandelplan', sa.Column('omvang_dienstverband', sa.Integer(), nullable=True))
    op.add_column('behandelplan', sa.Column('netto_inkomen', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('behandelplan', sa.Column('nu_arbeidsongeschikt', sa.Boolean(), nullable=True))
    op.add_column('behandelplan', sa.Column('percentage_arbeidsongeschikt', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('behandelplan', sa.Column('arbeidsongeschiktheid_startdatum', sa.Date(), nullable=True))
    op.add_column('behandelplan', sa.Column('arbeidsongeschiktheid_einddatum', sa.Date(), nullable=True))
    op.add_column('behandelplan', sa.Column('interventies', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('prognose', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('arbeid_overweging', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('samenstelling_huishouden', sa.String(length=100), nullable=True))
    op.add_column('behandelplan', sa.Column('aantal_kinderen', sa.Integer(), nullable=True))
    op.add_column('behandelplan', sa.Column('aandeel_huishoudelijke_taken', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('behandelplan', sa.Column('aandeel_zelfwerkzaamheid', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('behandelplan', sa.Column('nu_beperkt', sa.Boolean(), nullable=True))
    op.add_column('behandelplan', sa.Column('sociaal_startdatum', sa.Date(), nullable=True))
    op.add_column('behandelplan', sa.Column('sociaal_overweging', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('reden_lopend_dossier', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('oplossingsrichting', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('scenarios', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('vervolgstappen', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('motivering', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('ai_summary_dossierverloop', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('ai_summary_medisch', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('ai_summary_arbeid', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('ai_summary_sociaal', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('ai_summary_strategie', sa.Text(), nullable=True))
    op.add_column('behandelplan', sa.Column('ai_summary_overall', sa.Text(), nullable=True))
    op.drop_column('behandelplan', 'diagnosis')
    # Skip alter_column operations for SQLite compatibility - type changes are informational only
    # op.alter_column('signals', 'category', ...) 
    # op.alter_column('timeline', 'event_type', ...)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip alter_column operations for SQLite compatibility
    # op.alter_column('timeline', 'event_type', ...)
    # op.alter_column('signals', 'category', ...)
    op.add_column('behandelplan', sa.Column('diagnosis', sa.TEXT(), nullable=True))
    op.drop_column('behandelplan', 'ai_summary_overall')
    op.drop_column('behandelplan', 'ai_summary_strategie')
    op.drop_column('behandelplan', 'ai_summary_sociaal')
    op.drop_column('behandelplan', 'ai_summary_arbeid')
    op.drop_column('behandelplan', 'ai_summary_medisch')
    op.drop_column('behandelplan', 'ai_summary_dossierverloop')
    op.drop_column('behandelplan', 'motivering')
    op.drop_column('behandelplan', 'vervolgstappen')
    op.drop_column('behandelplan', 'scenarios')
    op.drop_column('behandelplan', 'oplossingsrichting')
    op.drop_column('behandelplan', 'reden_lopend_dossier')
    op.drop_column('behandelplan', 'sociaal_overweging')
    op.drop_column('behandelplan', 'sociaal_startdatum')
    op.drop_column('behandelplan', 'nu_beperkt')
    op.drop_column('behandelplan', 'aandeel_zelfwerkzaamheid')
    op.drop_column('behandelplan', 'aandeel_huishoudelijke_taken')
    op.drop_column('behandelplan', 'aantal_kinderen')
    op.drop_column('behandelplan', 'samenstelling_huishouden')
    op.drop_column('behandelplan', 'arbeid_overweging')
    op.drop_column('behandelplan', 'prognose')
    op.drop_column('behandelplan', 'interventies')
    op.drop_column('behandelplan', 'arbeidsongeschiktheid_einddatum')
    op.drop_column('behandelplan', 'arbeidsongeschiktheid_startdatum')
    op.drop_column('behandelplan', 'percentage_arbeidsongeschikt')
    op.drop_column('behandelplan', 'nu_arbeidsongeschikt')
    op.drop_column('behandelplan', 'netto_inkomen')
    op.drop_column('behandelplan', 'omvang_dienstverband')
    op.drop_column('behandelplan', 'dienstverband')
    op.drop_column('behandelplan', 'beroep')
    op.drop_column('behandelplan', 'medisch_advies')
    op.drop_column('behandelplan', 'datum_eindsituatie')
    op.drop_column('behandelplan', 'hersteld')
    op.drop_column('behandelplan', 'bijzonderheden_pre_existente')
    op.drop_column('behandelplan', 'beperkingen')
    op.drop_column('behandelplan', 'diagnose')
    op.drop_column('behandelplan', 'klachten')
    op.drop_column('behandelplan', 'dominante_zijde_beinvloedt')
    op.drop_column('behandelplan', 'letsel_zijde')
    op.drop_column('behandelplan', 'letselspecificatie')
    op.drop_column('behandelplan', 'letselsoort')
    op.drop_column('behandelplan', 'alle_of_niets_dossier')
    op.drop_column('behandelplan', 'regres_mogelijk')
    op.drop_column('behandelplan', 'percentage_eigen_schuld')
    op.drop_column('behandelplan', 'datum_aansprakelijkheid')
    op.drop_column('behandelplan', 'percentage_aansprakelijkheid')
    op.drop_column('behandelplan', 'dekking')
    op.drop_column('behandelplan', 'causaliteitsvraag')
    op.drop_column('behandelplan', 'toedracht')
    # ### end Alembic commands ###
